### ISSUE TITLE
Update data item names

### ISSUE THREAD

**Issue by brindakv** [salilab/modbase_utils#8]
Update `_ma_alignment_info.software_id` to `_ma_alignment_info.software_group_id` and `_ma_qa_metric.other_details` to `_ma_qa_metric.type_other_details` to match the dictionary.

**Comment by benmwebb** [comment]
Ah, I see the issue here. Output mmCIFs are validated by python-ihm, but they pass because both `_ma_alignment_info.software_group_id` and `_ma_qa_metric.type_other_details` are non-mandatory, and python-ihm doesn't complain about the extra data items `_ma_alignment_info.software_id` and `_ma_qa_metric.other_details` - but it should (I'll open a separate issue for that).
